In [115]:
import pandas as pd 
import numpy as np

In [116]:
#load main data set 
df = pd.read_csv("D:/nassau_profitability_project/data/raw/nassau_candy.csv")

#load mapping file 
product_factory = pd.read_csv("D:/nassau_profitability_project/data/mapping/product_factory_mapping.csv")
factory_coords = pd.read_csv("D:/nassau_profitability_project/data/mapping/factory_coordinates.csv")

In [117]:
# checking shape 
print("main data shape ", df.shape )
print("product factory shape ",product_factory.shape)
print ("factory coordinate shape ", factory_coords.shape)

main data shape  (10194, 18)
product factory shape  (15, 3)
factory coordinate shape  (5, 3)

In [118]:
#preview data
df.head ()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [119]:
product_factory.head()

    division                       product_name          factory
0  Chocolate  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
1  Chocolate          Wonka Bar - Fudge Mallows    Lot's O' Nuts
2  Chocolate     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
3  Chocolate         Wonka Bar - Milk Chocolate  Wicked Choccy's
4  Chocolate  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's

In [120]:
factory_coords.head()

             factory   latitude   longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [121]:
#standarlized column names 
df.columns = (df.columns
.str.strip()
.str.lower()
.str.replace("/","_", regex = False )
.str.replace (" ", "_", regex = False )
.str.replace ("-","_", regex = False))

product_factory.columns = (product_factory.columns.
                           str.strip()
                           )
factory_coords.columns = (factory_coords.columns .str . lower ())

In [122]:
print (df.columns.to_list())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'country_region', 'city', 'state_province', 'postal_code', 'division', 'region', 'product_id', 'product_name', 'sales', 'units', 'gross_profit', 'cost']

In [123]:
print(product_factory.columns. to_list())
print(factory_coords.columns.to_list())

['division', 'product_name', 'factory']
['factory', 'latitude', 'longitude']

In [124]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row_id          10194 non-null  int64
 1   order_id        10194 non-null  str
 2   order_date      10194 non-null  str
 3   ship_date       10194 non-null  str
 4   ship_mode       10194 non-null  str
 5   customer_id     10194 non-null  int64
 6   country_region  10194 non-null  str
 7   city            10194 non-null  str
 8   state_province  10194 non-null  str
 9   postal_code     10194 non-null  str
 10  division        10194 non-null  str
 11  region          10194 non-null  str
 12  product_id      10194 non-null  str
 13  product_name    10194 non-null  str
 14  sales           10194 non-null  float64
 15  units           10194 non-null  int64
 16  gross_profit    10194 non-null  float64
 17  cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB
None

In [125]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
row_id,10194.0,NaN,NaN,NaN,5097.5,2942.898656,1.0,2549.25,5097.5,7645.75,10194.0
order_id,10194,8549,US-2021-155502-CHO-MIL-31000,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,10194,717,02-09-2025,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship_date,10194,1338,07-06-2028,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship_mode,10194,4,Standard Class,6120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,10194.0,NaN,NaN,NaN,134468.961154,20231.483007,100006.0,117212.0,133550.0,152051.0,192314.0
country_region,10194,2,United States,9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,10194,542,New York City,915,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_province,10194,59,California,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
postal_code,10194,654,10035,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
division,10194,3,Chocolate,9844,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,10194,4,Pacific,3253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,10194,15,CHO-MIL-31000,2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name,10194,15,Wonka Bar - Milk Chocolate,2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sales,10194.0,NaN,NaN,NaN,13.908537,11.34102,1.25,7.2,10.8,18.0,260.0
units,10194.0,NaN,NaN,NaN,3.791838,2.228317,1.0,2.0,3.0,5.0,14.0
gross_profit,10194.0,NaN,NaN,NaN,9.166451,6.64374,0.25,4.9,7.47,12.25,130.0
cost,10194.0,NaN,NaN,NaN,4.742087,5.061647,0.6,2.4,3.6,5.7,130.0

In [126]:
#checking null values and sort them 
df.isnull().sum().sort_values(ascending=False)

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
country_region    0
city              0
state_province    0
postal_code       0
division          0
region            0
product_id        0
product_name      0
sales             0
units             0
gross_profit      0
cost              0
dtype: int64

In [127]:
#check duplicates 
print("duplicates rows : ", df.duplicated().sum())

duplicates rows :  0

In [128]:
text_columns = df.columns.astype(str)
print(text_columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost'],
      dtype='str')

In [129]:
text_cols = ['order_id','product_id','ship_mode','customer_id','country_region','city','state-province','divison','product_name',]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

In [130]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost'],
      dtype='str')

In [131]:
df['order_date'].head(10)

0    03-01-2024
1    04-01-2024
2    04-01-2024
3    04-01-2024
4    05-01-2024
5    06-01-2024
6    06-01-2024
7    06-01-2024
8    06-01-2024
9    06-01-2024
Name: order_date, dtype: str

In [ ]:
##convert date format
df["order_date"] = df["order_date"].astype(str).str.strip()

df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [136]:
df['ship_date'].head(10)

0    30-06-2026
1    01-07-2026
2    01-07-2026
3    01-07-2026
4    05-07-2026
5    03-07-2026
6    03-07-2026
7    30-06-2026
8    03-07-2026
9    03-07-2026
Name: ship_date, dtype: str

In [ ]:
#convert date format 
df["ship_date"] = df["ship_date"].astype(str).str.strip()

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [139]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
country_region    0
city              0
state_province    0
postal_code       0
division          0
region            0
product_id        0
product_name      0
sales             0
units             0
gross_profit      0
cost              0
dtype: int64

In [ ]:
#find numeric columns

In [ ]:
#convert numeric coluymns