In [1]:
import pandas as pd 
import numpy as np

In [3]:
#load main data set 
df = pd.read_csv("D:/nassau_profitability_project/data/raw/nassau_candy.csv")

#load mapping file 
product_factory = pd.read_csv("D:/nassau_profitability_project/data/mapping/product_factory_mapping.csv")
factory_coords = pd.read_csv("D:/nassau_profitability_project/data/mapping/factory_coordinates.csv")

In [4]:
# checking shape 
print("main data shape ", df.shape )
print("product factory shape ",product_factory.shape)
print ("factory coordinate shape ", factory_coords.shape)

main data shape  (10194, 18)
product factory shape  (15, 3)
factory coordinate shape  (5, 3)

In [10]:
#preview data
df.head ()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
product_factory.head()

    division                       product_name          factory
0  Chocolate  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
1  Chocolate          Wonka Bar - Fudge Mallows    Lot's O' Nuts
2  Chocolate     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
3  Chocolate         Wonka Bar - Milk Chocolate  Wicked Choccy's
4  Chocolate  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's

In [13]:
factory_coords.head()

             factory   latitude   longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [14]:
#standarlized column names 
df.columns = (df.columns
.str.strip()
.str.lower()
.str.replace("/","_", regex = False )
.str.replace (" ", "_", regex = False )
.str.replace ("-","_", regex = False))

product_factory.columns = (product_factory.columns.
                           str.strip()
                           )
factory_coords.columns = (factory_coords.columns .str . lower ())

In [16]:
print (df.columns.to_list())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'country_region', 'city', 'state_province', 'postal_code', 'division', 'region', 'product_id', 'product_name', 'sales', 'units', 'gross_profit', 'cost']

In [17]:
print(product_factory.columns. to_list())
print(factory_coords.columns.to_list())

['division', 'product_name', 'factory']
['factory', 'latitude', 'longitude']