In [3]:
import pandas as pd

product_summary = pd.read_csv("D:/nassau_profitability_project/data/processed/product_summary.csv")
division_summary = pd.read_csv("D:/nassau_profitability_project/data/processed/division_summary.csv")
monthly_summary = pd.read_csv("D:/nassau_profitability_project/data/processed/monthly_summary.csv")
factory_summary = pd.read_csv("D:/nassau_profitability_project/data/processed/factory_summary.csv")
pareto_profit = pd.read_csv("D:/nassau_profitability_project/outputs/tables/pareto_profit_table.csv")
pareto_revenue = pd.read_csv("D:/nassau_profitability_project/outputs/tables/pareto_revenue_table.csv")

2. Repricing candidates

These are products with:

-high sales
-low margin

This means demand is there, but margin quality is weak.

In [4]:
sales_threshold = product_summary["sales"].median()
margin_threshold = product_summary["gross_margin_pct"].median()

repricing_candidates = product_summary[
    (product_summary["sales"] >= sales_threshold) &
    (product_summary["gross_margin_pct"] < margin_threshold)
].sort_values(["sales", "gross_margin_pct"], ascending=[False, True])

repricing_candidates.head(10)

,product_id,product_name,division,sales,cost,gross_profit,units,total_orders,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,profit_rank,margin_rank,product_segment
8,OTH-LIC-15000,Lickable Wallpaper,Other,7860.00,3930.0,3930.00,393,92,50.000000,10.00,5.543658,4.205782,6.0,11.0,High Sales Low Margin
7,OTH-KAZ-38000,Kazookles,Other,1205.75,1113.0,92.75,371,94,7.692308,0.25,0.850416,0.099259,9.0,15.0,High Sales Low Margin
6,OTH-GUM-21000,Wonka Gum,Other,597.50,286.8,310.70,478,118,52.000000,0.65,0.421417,0.332503,7.0,10.0,High Sales Low Margin

In [5]:
repricing_candidates.to_csv("D:/nassau_profitability_project/outputs/tables/repricing_candidates.csv", index=False)

3.  Promotion candidates

These are products with:

-high margin
-low sales

This means product quality is strong, but market performance is underutilized.

In [6]:
promotion_candidates = product_summary[
    (product_summary["gross_margin_pct"] >= margin_threshold) &
    (product_summary["sales"] < sales_threshold)
].sort_values("gross_margin_pct", ascending=False)

promotion_candidates.head(10)

,product_id,product_name,division,sales,cost,gross_profit,units,total_orders,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,profit_rank,margin_rank,product_segment
9,SUG-EVE-47000,Everlasting Gobstopper,Sugar,130.00,26.00,104.00,13,3,80.000000,8.00,0.091689,0.111298,8.0,1.0,Star Product
11,SUG-HAI-55000,Hair Toffee,Sugar,76.50,17.00,59.50,17,4,77.777778,3.50,0.053955,0.063675,10.0,2.0,High Margin Low Sales
12,SUG-LAF-25000,Laffy Taffy,Sugar,53.73,20.25,33.48,27,10,62.311558,1.24,0.037896,0.035829,12.0,8.0,High Margin Low Sales

In [7]:
promotion_candidates.to_csv("D:/nassau_profitability_project/outputs/tables/promotion_candidates.csv", index=False)

4. Discontinuation review candidates

These are products with:

low sales
low profit
weak margin

These products may be hurting portfolio efficiency.

In [8]:
profit_threshold = product_summary["gross_profit"].median()

discontinue_candidates = product_summary[
    (product_summary["sales"] < sales_threshold) &
    (product_summary["gross_profit"] < profit_threshold) &
    (product_summary["gross_margin_pct"] < margin_threshold)
].sort_values(["gross_profit", "sales"], ascending=True)

discontinue_candidates.head(10)

,product_id,product_name,division,sales,cost,gross_profit,units,total_orders,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,profit_rank,margin_rank,product_segment
10,SUG-FUN-75000,Fun Dip,Sugar,12.00,7.2,4.80,8,3,40.000000,0.60,0.008464,0.005137,15.0,14.0,Low Performer
13,SUG-NER-92000,Nerds,Sugar,15.00,8.0,7.00,10,4,46.666667,0.70,0.010580,0.007491,14.0,12.5,Low Performer
14,SUG-SWE-91000,SweeTARTS,Sugar,61.50,32.8,28.70,41,10,46.666667,0.70,0.043376,0.030714,13.0,12.5,Low Performer
5,OTH-FIZ-56000,Fizzy Lifting Drinks,Sugar,78.75,31.5,47.25,21,6,60.000000,2.25,0.055542,0.050566,11.0,9.0,Low Performer

In [9]:
discontinue_candidates.to_csv("D:/nassau_profitability_project/outputs/tables/discontinue_review_candidates.csv", index=False)

5) Cost renegotiation candidates

We did not save cost_ratio in product summary earlier, so now create it first.

In [10]:
product_summary["cost_ratio"] = product_summary["cost"] / product_summary["sales"]

Now identify products where:

-cost ratio is high
-margin is low

In [11]:
cost_ratio_threshold = product_summary["cost_ratio"].median()

cost_renegotiation_candidates = product_summary[
    (product_summary["cost_ratio"] > cost_ratio_threshold) &
    (product_summary["gross_margin_pct"] < margin_threshold)
].sort_values(["cost_ratio", "gross_margin_pct"], ascending=[False, True])

cost_renegotiation_candidates.head(10)

,product_id,product_name,division,sales,cost,gross_profit,units,total_orders,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,profit_rank,margin_rank,product_segment,cost_ratio
7,OTH-KAZ-38000,Kazookles,Other,1205.75,1113.0,92.75,371,94,7.692308,0.25,0.850416,0.099259,9.0,15.0,High Sales Low Margin,0.923077
10,SUG-FUN-75000,Fun Dip,Sugar,12.00,7.2,4.80,8,3,40.000000,0.60,0.008464,0.005137,15.0,14.0,Low Performer,0.600000
13,SUG-NER-92000,Nerds,Sugar,15.00,8.0,7.00,10,4,46.666667,0.70,0.010580,0.007491,14.0,12.5,Low Performer,0.533333
14,SUG-SWE-91000,SweeTARTS,Sugar,61.50,32.8,28.70,41,10,46.666667,0.70,0.043376,0.030714,13.0,12.5,Low Performer,0.533333
8,OTH-LIC-15000,Lickable Wallpaper,Other,7860.00,3930.0,3930.00,393,92,50.000000,10.00,5.543658,4.205782,6.0,11.0,High Sales Low Margin,0.500000
6,OTH-GUM-21000,Wonka Gum,Other,597.50,286.8,310.70,478,118,52.000000,0.65,0.421417,0.332503,7.0,10.0,High Sales Low Margin,0.480000
5,OTH-FIZ-56000,Fizzy Lifting Drinks,Sugar,78.75,31.5,47.25,21,6,60.000000,2.25,0.055542,0.050566,11.0,9.0,Low Performer,0.400000

In [12]:
cost_renegotiation_candidates.to_csv("D:/nassau_profitability_project/outputs/tables/cost_renegotiation_candidates.csv", index=False)

6) Star products

These are your strongest products.

In [13]:
star_products = product_summary[
    (product_summary["gross_profit"] >= profit_threshold) &
    (product_summary["gross_margin_pct"] >= margin_threshold)
].sort_values(["gross_profit", "gross_margin_pct"], ascending=False)

star_products.head(10)

,product_id,product_name,division,sales,cost,gross_profit,units,total_orders,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,profit_rank,margin_rank,product_segment,cost_ratio
3,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,Chocolate,27874.80,8517.30,19357.50,7743,1704,69.444444,2.50,19.660098,20.715882,1.0,4.0,Star Product,0.305556
4,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,Chocolate,28485.00,9874.80,18610.20,7596,1677,65.333333,2.45,20.090472,19.916141,2.0,6.0,Star Product,0.346667
1,CHO-MIL-31000,Wonka Bar - Milk Chocolate,Chocolate,26867.75,9424.38,17443.37,8267,1768,64.923077,2.11,18.949825,18.667431,3.0,7.0,Star Product,0.350769
2,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,Chocolate,23574.95,6755.00,16819.95,6755,1529,71.346705,2.49,16.627413,18.000263,4.0,3.0,Star Product,0.286533
0,CHO-FUD-51000,Wonka Bar - Fudge Mallows,Chocolate,24890.40,8296.80,16593.60,6914,1527,66.666667,2.40,17.555200,17.758030,5.0,5.0,Star Product,0.333333
9,SUG-EVE-47000,Everlasting Gobstopper,Sugar,130.00,26.00,104.00,13,3,80.000000,8.00,0.091689,0.111298,8.0,1.0,Star Product,0.200000

In [14]:
star_products.to_csv("D:/nassau_profitability_project/outputs/tables/star_products.csv", index=False)

7) Revenue vs profit imbalance insight table

Create a difference column.

In [15]:
division_summary["contribution_gap"] = (
    division_summary["profit_contribution_pct"] - division_summary["revenue_contribution_pct"]
)

division_imbalance = division_summary.sort_values("contribution_gap")
division_imbalance

,division,sales,cost,gross_profit,units,gross_margin_pct,profit_per_unit,revenue_contribution_pct,profit_contribution_pct,contribution_gap
1,Other,9663.25,5329.80,4333.45,1242,44.844643,3.489090,6.815491,4.637543,-2.177948
2,Sugar,427.48,142.75,284.73,137,66.606625,2.078321,0.301502,0.304710,0.003209
0,Chocolate,131692.90,42868.28,88824.62,37275,67.448298,2.382954,92.883008,95.057747,2.174739

Interpretation:

negative gap → revenue is strong but profit is weaker
positive gap → division is more efficient than its revenue share suggests

In [16]:
division_imbalance.to_csv("D:/nassau_profitability_project/outputs/tables/division_imbalance.csv", index=False)

8) Profit concentration risk insight

Find how many products contribute 80% of profit.

In [17]:
profit_80_count = (pareto_profit["cumulative_profit_pct"] <= 80).sum()
revenue_80_count = (pareto_revenue["cumulative_sales_pct"] <= 80).sum()

total_products = product_summary.shape[0]

profit_80_pct_products = (profit_80_count / total_products) * 100
revenue_80_pct_products = (revenue_80_count / total_products) * 100

print("Products contributing 80% of profit:", profit_80_count)
print("Products contributing 80% of revenue:", revenue_80_count)
print("Percent of products contributing 80% of profit:", round(profit_80_pct_products, 2))
print("Percent of products contributing 80% of revenue:", round(revenue_80_pct_products, 2))

Products contributing 80% of profit: 4
Products contributing 80% of revenue: 4
Percent of products contributing 80% of profit: 26.67
Percent of products contributing 80% of revenue: 26.67

In [18]:
# store in small table 
concentration_summary = pd.DataFrame({
    "metric": ["80% Profit Concentration", "80% Revenue Concentration"],
    "product_count": [profit_80_count, revenue_80_count],
    "percent_of_total_products": [profit_80_pct_products, revenue_80_pct_products]
})

concentration_summary

                      metric  product_count  percent_of_total_products
0   80% Profit Concentration              4                  26.666667
1  80% Revenue Concentration              4                  26.666667

In [19]:
concentration_summary.to_csv("D:/nassau_profitability_project/outputs/tables/concentration_summary.csv", index=False)

9) Factory efficiency insight

Add contribution metrics to factory summary.

In [20]:
factory_summary["revenue_contribution_pct"] = (
    factory_summary["sales"] / factory_summary["sales"].sum()
) * 100

factory_summary["profit_contribution_pct"] = (
    factory_summary["gross_profit"] / factory_summary["gross_profit"].sum()
) * 100

factory_summary["gross_margin_pct"] = (factory_summary["gross_profit"] / factory_summary["sales"]) * 100

factory_summary.sort_values("gross_profit", ascending=False)

,factory,sales,cost,gross_profit,units,gross_margin_pct,revenue_contribution_pct,profit_contribution_pct
0,Lot's O' Nuts,76340.15,23569.10,52771.05,21412,69.126207,53.842711,56.474175
5,Wicked Choccy's,55352.75,19299.18,36053.57,15863,65.134198,39.040297,38.583572
1,Secret Factory,8587.50,4242.80,4344.70,884,50.593304,6.056764,4.649582
3,The Other Factory,1282.25,1130.00,152.25,388,11.873660,0.904371,0.162934
2,Sugar Shack,142.23,68.25,73.98,86,52.014343,0.100315,0.079171
4,Unknown,78.75,31.50,47.25,21,60.000000,0.055542,0.050566

In [21]:
factory_summary.to_csv("D:/nassau_profitability_project/outputs/tables/factory_efficiency_summary.csv", index=False)

10) Create action recommendation column

This is very useful for dashboard and report.

In [22]:
def recommendation(row):
    if row["sales"] >= sales_threshold and row["gross_margin_pct"] < margin_threshold:
        return "Reprice"
    elif row["cost_ratio"] > cost_ratio_threshold and row["gross_margin_pct"] < margin_threshold:
        return "Renegotiate Cost"
    elif row["gross_margin_pct"] >= margin_threshold and row["sales"] < sales_threshold:
        return "Promote"
    elif row["sales"] < sales_threshold and row["gross_profit"] < profit_threshold:
        return "Discontinue Review"
    else:
        return "Monitor"

product_summary["recommended_action"] = product_summary.apply(recommendation, axis=1)
product_summary[["product_name", "division", "gross_profit", "gross_margin_pct", "recommended_action"]].head(10)

,product_name,division,gross_profit,gross_margin_pct,recommended_action
0,Wonka Bar - Fudge Mallows,Chocolate,16593.60,66.666667,Monitor
1,Wonka Bar - Milk Chocolate,Chocolate,17443.37,64.923077,Monitor
2,Wonka Bar - Nutty Crunch Surprise,Chocolate,16819.95,71.346705,Monitor
3,Wonka Bar -Scrumdiddlyumptious,Chocolate,19357.50,69.444444,Monitor
4,Wonka Bar - Triple Dazzle Caramel,Chocolate,18610.20,65.333333,Monitor
5,Fizzy Lifting Drinks,Sugar,47.25,60.000000,Renegotiate Cost
6,Wonka Gum,Other,310.70,52.000000,Reprice
7,Kazookles,Other,92.75,7.692308,Reprice
8,Lickable Wallpaper,Other,3930.00,50.000000,Reprice
9,Everlasting Gobstopper,Sugar,104.00,80.000000,Promote

In [23]:
product_summary.to_csv("D:/nassau_profitability_project/outputs/tables/product_summary_with_actions.csv", index=False)